### ISSUE TITLE
Figure 2 - Processor

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/gages-through-ages#11]
- [x] process fetched data into smoothed (smoothed over 1-2 month window)  sparkline data for timeline (all years) 
- [x] process into day of year discharge for all years (site, discharge, day of year, year)

**Comment by lindsayplatt** [comment]
what exactly are we talking about by "smoothed" over 1-2 months? Is that the average between those 2 months?

**Comment by lindsayplatt** [comment]
@jread-usgs @eread-usgs :point_up:

**Comment by jordansread** [comment]
An adjustable window for smoothing the data. So we don't plot the extreme daily peaks

**Comment by lindsayplatt** [comment]
Still not really following how to implement that in process...

**Comment by jordansread** [comment]
a parameter for the window over which to average (smooth) the data. Like `smooth.days`

**Comment by lindsayplatt** [comment]
ah OK, so smooth is referring to averaging over that window. Got it now.

**Comment by ldecicco-USGS** [comment]
![image](https://cloud.githubusercontent.com/assets/1105215/23727154/83cac15a-041c-11e7-9af1-aff9eb60b6a5.png)

**Comment by jordansread** [comment]
yes ☝️ smoothing
