### ISSUE TITLE
Formalize code for getting gage data

### ISSUE THREAD

**Issue by eread-usgs** [USGS-VIZLAB/gages-through-ages#2]
- [x] Meet OSW standards for 'year complete' 
- [x] Review other rules from Robert Mason
- [x] Once data are in hand, get into SB

**Comment by jordansread** [comment]
make sure we capture site, lat, lon, huc, etc.

**Comment by wdwatkins** [comment]
Unfortunately, hitting the 355 day standard means pulling 10k sites vs about 6k sites from NWIS.  Fortunately, I can cheat somewhat since I still have all the 6k sites downloaded from last time, and I can only download the new ones.

**Comment by wdwatkins** [comment]
#30

**Comment by wdwatkins** [comment]
https://www.sciencebase.gov/catalog/item/58c18c7ae4b014cc3a3d3706?groupId=JQUERY-FILE-UPLOAD-e82437ad-3cd1-4c8c-b879-aa0670dd7730  

Final output on SB

**Comment by eread-usgs** [comment]
Can we consider this 'closed' @wdwatkins ?

**Comment by wdwatkins** [comment]
yep
