### ISSUE TITLE
adding lots of child nodes one by one gets slower and slower

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/gages-through-ages#29]
looping through a set of nodes and adding them one by one is fast...for a while. Then it gets slow, and slower, and slower. 

This is an issue when moving the "site" dots from one part of the DOM to another, since there are > 10,000 sites. (not an issue w/ states and other things because of the smaller number). 

There has to be a faster way to do this. 

Reproducible example:
```r
svg <- svglite::xmlSVG({
   plot(1,1)
})
library(xml2)
for (i in 1:1000){
    id.name <- paste0('nwis-',i)
    xml_add_child(svg, 'circle', r="2", id=id.name)
    message('done with ',i, ' of ', 1000)
  }
```
w/o the message in there, I'm sure it is faster, but w/ the message, you will see it start to slow down before 1000

**Comment by jordansread** [comment]
Is there a solution that allows us to add `circle` nodes in bulk?

**Comment by jordansread** [comment]
perhaps starting w/ https://github.com/hadley/xml2/blob/b3104813cc07e8261a54f1307303f5d31702ed8e/R/as_xml_document.R?

**Comment by jordansread** [comment]
This pattern seems to be an improvement:
```r
c.list <- list()
  for (i in 1:length(site.num)){
    id.name <- paste0('nwis-',site.num[i])
    c.list <- append(c.list, list(
      circle = structure(list(), 
                         id = id.name, cx = cxs[i], cy = cys[i], r="2")))
  }
  
  g.sites <- as_xml_document(list(g = c.list))
  attr(g.sites,'id') <- 'site-circles'
  
  xml_add_child(svg, g.sites)
```

**Comment by jordansread** [comment]
Geez, and now it seems the bottleneck is `as_xml_document(list(g = c.list))`

**Comment by jordansread** [comment]
Setting this as `wontfix` for now https://github.com/hadley/xml2/issues/170

**Comment by wdwatkins** [comment]
Is there a way you can preallocate empty nodes and then fill them?

**Comment by jimhester** [comment]
I think you are going to run into issues trying to iteratively add nodes to a document. If you have a large block of nodes it will probably be faster to write the content as text and parse them as a block, then insert the whole block into the existing document in one call.

**Comment by jordansread** [comment]
Thanks @jimhester that is what we ended up doing for this.
