### ISSUE TITLE
use diffs per year in the years-data.json

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/gages-through-ages#41]
from walker:
1968 = 1967 + x - y

since our years.json is large (2MB) and has a lot of redundancy

**Comment by jordansread** [comment]
This will require changing the process step and adapting to that change in the JS

**Comment by jordansread** [comment]
@jiwalker-usgs when you get a chance, can you provide guidance as to what format you would like this to appear as?

for example, 
```json
{"sites-group-1":{"1980":[774,775,-45,-24]}}
```
Would be my guess to say that we gain sites 774, 775 and lost 45 and 24.. ?

**Comment by jiwalker-usgs** [comment]
I think that format would be fine, otherwise splitting into two arrays would work reasonably as well:

```
{"sites-group-1":{"1980":{"gain":[774,775],"loss":[45,24]}}}
```

**Comment by jordansread** [comment]
Oh, didn't see that @jiwalker-usgs , but I was close ;)
