### ISSUE TITLE
deal with empty paths on vizlab.showyear()

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/gages-through-ages#50]
e.g.
vizlab.showyear(1890)
9jquery311.min.js?_c=1273721:4 Error: <path> attribute d: Unexpected end of attribute. Expected number, "M".

Guessing this is because it tries to build an empty path. When that happens, we could take that group and make it `M0,0` (or something), which keeps the path but won't render anything

**Comment by jordansread** [comment]
@mbucknell want to take this?

**Comment by jiwalker-usgs** [comment]
@jread-usgs this is on me, I didn't have all the edge cases handled, PR coming shortly

**Comment by jiwalker-usgs** [comment]
Should be good with #55
