### ISSUE TITLE
add bar chart connection to vizlab.showyear(year)

### ISSUE THREAD

**Issue by jordansread** [USGS-VIZLAB/gages-through-ages#58]
This should redraw the points on the map, but should also give us the proper emphasis on the bars. 

my suggestion is to flip all bars to a class w/ low opacity, then flip all bars < `year` to a class w/ a higher opacity, and then the bar == `year` to the "emphasize" class (whatever that may be).

**Comment by mbucknell** [comment]
I have this working now so that the selected year is red. I'm not sure I see the purpose of styling the bars less than the selected year different from the ones greater than the selected year.

**Comment by jordansread** [comment]
this is complete
